<a href="https://colab.research.google.com/github/MaximTislenko/GeekBrains/blob/main/Colaboratory_08_06_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лекция №2

In [1]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%late

##Важно
***Для пользователей Jupyter: Magics специфичны для ядра IPython и предоставляются им. Решение о том, доступны ли Magics в ядре, принимается разработчиком ядра отдельно для каждого ядра. Для правильной работы Magics должен использовать элемент синтаксиса, недопустимый в базовом языке. Например, ядро IPython использует синтаксический элемент % для Magics, поскольку % не является допустимым унарным оператором в Python. Однако % может иметь значение на других языках.***

##Магия линий
####%alias - Определите псевдоним для системной команды. *%alias alias_name cmd* определяет *alias_name* как псевдоним для *cmd* . Затем при вводе «alias_name params» будет выполнена системная команда «cmd params» (из базовой операционной системы). Псевдонимы имеют более низкий приоритет, чем магические функции и обычные переменные Python, поэтому, если «foo» является одновременно переменной Python и псевдонимом, псевдоним не может быть выполнен до тех пор, пока «del foo» не удалит переменную Python. Вы можете использовать спецификатор %l в определении псевдонима для представления всей строки при вызове псевдонима. Например:
* In [2]: alias bracket echo "Input in brackets: <%l>"
* In [3]: bracket hello world
* Input in brackets: <hello world>

####Вы также можете определить псевдонимы с параметрами, используя спецификаторы %s (по одному на параметр):

* In [1]: alias parts echo first %s second %s
* In [2]: %parts A B
* first A second B
* In [3]: %parts A
* Incorrect number of arguments: 2 expected.
* parts is an alias to: 'echo first %s second %s'



###Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

###Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%shell  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Автомагия включена, префикс % НЕ нужен для магии линий.

##Примеры
* *%run имя_скрипта.py* - выполнение скрипта Python, результат будет внутри колаба
* *%load имя_скрипта.py* - сама команда законектится, а код окажется в ячейке
* *%pycat имя_скрипта.py* - код окажется в нижней части страницы
* *%%time* - за какое время выполнились команды содержащиеся в ячейке
* *%%timeit* - время для быстрых команд

In [13]:
%%time
for i in range(100):
  for y in range(100):
    for r in range(100):
      pass

CPU times: user 31 ms, sys: 941 µs, total: 32 ms
Wall time: 33.5 ms


In [15]:
%%timeit
2**1000

1.03 µs ± 324 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


##Запуск команд операционной системы

In [22]:
!help dir -p

dirs: dirs [-clpv] [+N] [-N]
    Display directory stack.
    
    Display the list of currently remembered directories.  Directories
    find their way onto the list with the `pushd' command; you can get
    back up through the list with the `popd' command.
    
    Options:
      -c	clear the directory stack by deleting all of the elements
      -l	do not print tilde-prefixed versions of directories relative
    		to your home directory
      -p	print the directory stack with one entry per line
      -v	print the directory stack with one entry per line prefixed
    		with its position in the stack
    
    Arguments:
      +N	Displays the Nth entry counting from the left of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
      -N	Displays the Nth entry counting from the right of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
    Exit Status:
    Returns success unless an invalid option is supplied or

In [24]:
!dir sample_data/ -p

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


#Numpy

In [25]:
import numpy as np

##Создание многомерных массивов Numpy

In [29]:
a = [i for i in range(10, 40, 2)] # Это список
print(a)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [31]:
b = np.array(a)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [32]:
type(b)

numpy.ndarray

In [33]:
b = np.array(a, dtype=float )
b

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38.])

In [34]:
b = np.array(a, dtype=int)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [35]:
b = np.array(a, dtype=str)
b

array(['10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30',
       '32', '34', '36', '38'], dtype='<U2')

##Доступ к элементам массива

##Изменение и копирование массивов

##Типы данных Numpy