<a href="https://colab.research.google.com/github/MaximTislenko/GeekBrains/blob/main/Less_02_A_22062023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лекция №2

In [ ]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%late

##Важно
***Для пользователей Jupyter: Magics специфичны для ядра IPython и предоставляются им. Решение о том, доступны ли Magics в ядре, принимается разработчиком ядра отдельно для каждого ядра. Для правильной работы Magics должен использовать элемент синтаксиса, недопустимый в базовом языке. Например, ядро IPython использует синтаксический элемент % для Magics, поскольку % не является допустимым унарным оператором в Python. Однако % может иметь значение на других языках.***

##Магия линий
####%alias - Определите псевдоним для системной команды. *%alias alias_name cmd* определяет *alias_name* как псевдоним для *cmd* . Затем при вводе «alias_name params» будет выполнена системная команда «cmd params» (из базовой операционной системы). Псевдонимы имеют более низкий приоритет, чем магические функции и обычные переменные Python, поэтому, если «foo» является одновременно переменной Python и псевдонимом, псевдоним не может быть выполнен до тех пор, пока «del foo» не удалит переменную Python. Вы можете использовать спецификатор %l в определении псевдонима для представления всей строки при вызове псевдонима. Например:
* In [2]: alias bracket echo "Input in brackets: <%l>"
* In [3]: bracket hello world
* Input in brackets: <hello world>

####Вы также можете определить псевдонимы с параметрами, используя спецификаторы %s (по одному на параметр):

* In [1]: alias parts echo first %s second %s
* In [2]: %parts A B
* first A second B
* In [3]: %parts A
* Incorrect number of arguments: 2 expected.
* parts is an alias to: 'echo first %s second %s'



###Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

###Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%shell  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Автомагия включена, префикс % НЕ нужен для магии линий.

##Примеры
* *%run имя_скрипта.py* - выполнение скрипта Python, результат будет внутри колаба
* *%load имя_скрипта.py* - сама команда законектится, а код окажется в ячейке
* *%pycat имя_скрипта.py* - код окажется в нижней части страницы
* *%%time* - за какое время выполнились команды содержащиеся в ячейке
* *%%timeit* - время для быстрых команд

In [ ]:
%%time
for i in range(100):
  for y in range(100):
    for r in range(100):
      pass

CPU times: user 51.9 ms, sys: 0 ns, total: 51.9 ms
Wall time: 70 ms


In [ ]:
%%timeit
2**1000

827 ns ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


##Запуск команд операционной системы

In [ ]:
!help dir -p

dirs: dirs [-clpv] [+N] [-N]
    Display directory stack.
    
    Display the list of currently remembered directories.  Directories
    find their way onto the list with the `pushd' command; you can get
    back up through the list with the `popd' command.
    
    Options:
      -c	clear the directory stack by deleting all of the elements
      -l	do not print tilde-prefixed versions of directories relative
    		to your home directory
      -p	print the directory stack with one entry per line
      -v	print the directory stack with one entry per line prefixed
    		with its position in the stack
    
    Arguments:
      +N	Displays the Nth entry counting from the left of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
      -N	Displays the Nth entry counting from the right of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
    Exit Status:
    Returns success unless an invalid option is supplied or

In [ ]:
!dir sample_data/ -p

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


#Numpy

In [ ]:
import numpy as np

##Создание многомерных массивов Numpy

In [ ]:
a = [i for i in range(10, 40, 2)] # Это список
print(a)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [ ]:
b = np.array(a)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b = np.array(a, dtype=float )
b

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38.])

In [ ]:
b = np.array(a, dtype=int)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [ ]:
b = np.array(a, dtype=str)
b

array(['10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30',
       '32', '34', '36', '38'], dtype='<U2')

###Если один из элементов массива имеет отличный тип данных, то остальные будутут такимиже без указания.

In [ ]:
a = [1, 2, 3, 'abc']
b = np.array(a)
b

array(['1', '2', '3', 'abc'], dtype='<U21')

In [ ]:
a = [1, 2, 3, 'abc']
b = np.array(a, dtype=int)
b

ValueError: ignored

In [ ]:
a = [1, 2, 3, 4.125]
b= np.array(a)
b

array([1.   , 2.   , 3.   , 4.125])

In [ ]:
b.dtype

dtype('float64')

###Получаем элементы массива

In [ ]:
b[0]

1.0

In [ ]:
b[3]

4.125

In [ ]:
b[:2]

array([1., 2.])

In [ ]:
b[-1]

4.125

###Размерность массива

In [ ]:
b.ndim

1

In [ ]:
type(b.ndim)

int

In [ ]:
b.shape

(4,)

In [ ]:
type(b.shape)

tuple

In [ ]:
b.size #Общее количество элементов

4

In [ ]:
type(b.size)

int

###Двух-мерный массив (2d array)

In [ ]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
             [10,11,12,13,14,15,16,17,18,19],
             [20,21,22,23,24,25,26,27,28,29]])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [ ]:
b.shape # 3-строки и 10-колонок

(3, 10)

In [ ]:
b.size #общее количество элементов

30

##Доступ к элементам массива

In [ ]:
b[1][1]

11

###Можно через запятую

In [ ]:
b[1, 1]

11

In [ ]:
b[0:2, 2:7] #Срезы

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16]])

In [ ]:
b[1:, 5:] #Срезы

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

##Изменение и копирование массивов

###Создадим новый массив *c* из среза массива *b*

In [ ]:
c = b[1:, 5:]# Это не новый массив, это ссылка на массив
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [ ]:
c[1, 4] = 999
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [ ]:
b #ВАЖНО: Изменеия вносятся и в массив 'b'

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

###Для того, чтобы массивы были независимы нужно применять метод *.copy()*

In [ ]:
c = b[1:, 4:].copy()
c

array([[ 14,  15,  16,  17,  18,  19],
       [ 24,  25,  26,  27,  28, 999]])

In [ ]:
c[1, 5] = 29
c

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [ ]:
b[2, 9] = 29
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

##Типы данных Numpy

In [ ]:
f = np.array([1, 2, 3], dtype=np.float64)
print(f.dtype, f)

float64 [1. 2. 3.]


In [ ]:
f = np.array([1, 2, 3], dtype=np.float32)
print(f.dtype, f)

float32 [1. 2. 3.]


In [ ]:
f = np.array([1, 2, 3], dtype=np.int32)
print(f.dtype, f)

int32 [1 2 3]


In [ ]:
f = np.array([1, 2, 3], dtype=np.int64)
print(f.dtype, f)

int64 [1 2 3]


In [ ]:
f = np.array([[1, 2, 3],[4, 5, 6]],
             dtype=np.string_) #При использовании в массивах этот тип удаляет завершающие нулевые байты.
print(f.dtype, f)

|S1 [[b'1' b'2' b'3']
 [b'4' b'5' b'6']]


In [ ]:
f = np.array([1, 2, 3], dtype=np.str0)
print(f.dtype, f)

<U1 ['1' '2' '3']


#Применение Nympy для линейной алгебры - Часть 1

In [1]:
import numpy as np

##Сложение и вычитание векторов

##Умножение вектора на скаляр

##Скалярное произведение векторов

##Сложение и вычитание матриц

##Умножение матрицы на скаляр