<a href="https://colab.research.google.com/github/MaximTislenko/GeekBrains/blob/main/Less_02_A_22_06_2023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Лекция №2

In [74]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%late

##Важно
***Для пользователей Jupyter: Magics специфичны для ядра IPython и предоставляются им. Решение о том, доступны ли Magics в ядре, принимается разработчиком ядра отдельно для каждого ядра. Для правильной работы Magics должен использовать элемент синтаксиса, недопустимый в базовом языке. Например, ядро IPython использует синтаксический элемент % для Magics, поскольку % не является допустимым унарным оператором в Python. Однако % может иметь значение на других языках.***

##Магия линий
####%alias - Определите псевдоним для системной команды. *%alias alias_name cmd* определяет *alias_name* как псевдоним для *cmd* . Затем при вводе «alias_name params» будет выполнена системная команда «cmd params» (из базовой операционной системы). Псевдонимы имеют более низкий приоритет, чем магические функции и обычные переменные Python, поэтому, если «foo» является одновременно переменной Python и псевдонимом, псевдоним не может быть выполнен до тех пор, пока «del foo» не удалит переменную Python. Вы можете использовать спецификатор %l в определении псевдонима для представления всей строки при вызове псевдонима. Например:
* In [2]: alias bracket echo "Input in brackets: <%l>"
* In [3]: bracket hello world
* Input in brackets: <hello world>

####Вы также можете определить псевдонимы с параметрами, используя спецификаторы %s (по одному на параметр):

* In [1]: alias parts echo first %s second %s
* In [2]: %parts A B
* first A second B
* In [3]: %parts A
* Incorrect number of arguments: 2 expected.
* parts is an alias to: 'echo first %s second %s'



###Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %shell  %store  %sx  %system  %tb  %tensorflow_version  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

###Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%bigquery  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%shell  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Автомагия включена, префикс % НЕ нужен для магии линий.

##Примеры
* *%run имя_скрипта.py* - выполнение скрипта Python, результат будет внутри колаба
* *%load имя_скрипта.py* - сама команда законектится, а код окажется в ячейке
* *%pycat имя_скрипта.py* - код окажется в нижней части страницы
* *%%time* - за какое время выполнились команды содержащиеся в ячейке
* *%%timeit* - время для быстрых команд

In [75]:
%%time
for i in range(100):
  for y in range(100):
    for r in range(100):
      pass

CPU times: user 45.1 ms, sys: 0 ns, total: 45.1 ms
Wall time: 45.2 ms


In [76]:
%%timeit
2**1000

1.05 µs ± 276 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


##Запуск команд операционной системы

In [77]:
!help dir -p

dirs: dirs [-clpv] [+N] [-N]
    Display directory stack.
    
    Display the list of currently remembered directories.  Directories
    find their way onto the list with the `pushd' command; you can get
    back up through the list with the `popd' command.
    
    Options:
      -c	clear the directory stack by deleting all of the elements
      -l	do not print tilde-prefixed versions of directories relative
    		to your home directory
      -p	print the directory stack with one entry per line
      -v	print the directory stack with one entry per line prefixed
    		with its position in the stack
    
    Arguments:
      +N	Displays the Nth entry counting from the left of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
      -N	Displays the Nth entry counting from the right of the list
    		shown by dirs when invoked without options, starting with
    		zero.
    
    Exit Status:
    Returns success unless an invalid option is supplied or

In [78]:
!dir sample_data/ -p

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


#Numpy

In [79]:
import numpy as np

##Создание многомерных массивов Numpy

In [80]:
a = [i for i in range(10, 40, 2)] # Это список
print(a)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]


In [81]:
b = np.array(a)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [82]:
type(b)

numpy.ndarray

In [83]:
b = np.array(a, dtype=float )
b

array([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30., 32., 34.,
       36., 38.])

In [84]:
b = np.array(a, dtype=int)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [85]:
b = np.array(a, dtype=str)
b

array(['10', '12', '14', '16', '18', '20', '22', '24', '26', '28', '30',
       '32', '34', '36', '38'], dtype='<U2')

###Если один из элементов массива имеет отличный тип данных, то остальные будутут такимиже без указания.

In [86]:
a = [1, 2, 3, 'abc']
b = np.array(a)
b

array(['1', '2', '3', 'abc'], dtype='<U21')

In [154]:
a = [1, 2, 3, 'abc']
b = np.array(a, dtype=int)
b

ValueError: ignored

In [88]:
a = [1, 2, 3, 4.125]
b= np.array(a)
b

array([1.   , 2.   , 3.   , 4.125])

In [89]:
b.dtype

dtype('float64')

###Получаем элементы массива

In [90]:
b[0]

1.0

In [91]:
b[3]

4.125

In [92]:
b[:2]

array([1., 2.])

In [93]:
b[-1]

4.125

###Размерность массива

In [94]:
b.ndim

1

In [95]:
type(b.ndim)

int

In [96]:
b.shape

(4,)

In [97]:
type(b.shape)

tuple

In [98]:
b.size #Общее количество элементов

4

In [99]:
type(b.size)

int

###Двух-мерный массив (2d array)

In [100]:
b = np.array([[0,1,2,3,4,5,6,7,8,9],
             [10,11,12,13,14,15,16,17,18,19],
             [20,21,22,23,24,25,26,27,28,29]])
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [101]:
b.shape # 3-строки и 10-колонок

(3, 10)

In [102]:
b.size #общее количество элементов

30

##Доступ к элементам массива

In [103]:
b[1][1]

11

###Можно через запятую

In [104]:
b[1, 1]

11

In [105]:
b[0:2, 2:7] #Срезы

array([[ 2,  3,  4,  5,  6],
       [12, 13, 14, 15, 16]])

In [106]:
b[1:, 5:] #Срезы

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

##Изменение и копирование массивов

###Создадим новый массив *c* из среза массива *b*

In [107]:
c = b[1:, 5:]# Это не новый массив, это ссылка на массив
c

array([[15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [108]:
c[1, 4] = 999
c

array([[ 15,  16,  17,  18,  19],
       [ 25,  26,  27,  28, 999]])

In [109]:
b #ВАЖНО: Изменеия вносятся и в массив 'b'

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

###Для того, чтобы массивы были независимы нужно применять метод *.copy()*

In [110]:
c = b[1:, 4:].copy()
c

array([[ 14,  15,  16,  17,  18,  19],
       [ 24,  25,  26,  27,  28, 999]])

In [111]:
c[1, 5] = 29
c

array([[14, 15, 16, 17, 18, 19],
       [24, 25, 26, 27, 28, 29]])

In [112]:
b

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28, 999]])

In [113]:
b[2, 9] = 29
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

##Типы данных Numpy

In [114]:
f = np.array([1, 2, 3], dtype=np.float64)
print(f.dtype, f)

float64 [1. 2. 3.]


In [115]:
f = np.array([1, 2, 3], dtype=np.float32)
print(f.dtype, f)

float32 [1. 2. 3.]


In [116]:
f = np.array([1, 2, 3], dtype=np.int32)
print(f.dtype, f)

int32 [1 2 3]


In [117]:
f = np.array([1, 2, 3], dtype=np.int64)
print(f.dtype, f)

int64 [1 2 3]


In [118]:
f = np.array([[1, 2, 3],[4, 5, 6]],
             dtype=np.string_) #При использовании в массивах этот тип удаляет завершающие нулевые байты.
print(f.dtype, f)

|S1 [[b'1' b'2' b'3']
 [b'4' b'5' b'6']]


In [119]:
f = np.array([1, 2, 3], dtype=np.str0)
print(f.dtype, f)

<U1 ['1' '2' '3']


#Применение Nympy для линейной алгебры - Часть 1

In [120]:
import numpy as np

##Сложение и вычитание векторов

In [121]:
a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [122]:
b = np.array([5, 6, 7, 8, 9])
b

array([5, 6, 7, 8, 9])

In [123]:
print('a - ', a.size, a.shape)
print('b - ', b.size, b.shape)

a -  5 (5,)
b -  5 (5,)


###Сложение

In [124]:
c = a + b
print(c)
print(c.size, c.shape)

[ 5  7  9 11 13]
5 (5,)


In [125]:
print(a)
print(b)
print(c)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]


In [126]:
c = np.add(a, b)
c

array([ 5,  7,  9, 11, 13])

Массивы должны быть одинакового размера, если масивы разные то вылезет либо ошибка, либо дополнительные свойства.

###Вычитание

In [127]:
f = np.array([5, 4, 8, 4, 3])
k = np.array([3, 5, 7, 1, 3])

In [128]:
d = f - k
d

array([ 2, -1,  1,  3,  0])

In [129]:
d = np.subtract(f, k)
d

array([ 2, -1,  1,  3,  0])

Массивы должны быть одинакового рамера

In [130]:
f.shape == k.shape

True

##Умножение вектора на скаляр

In [131]:
f

array([5, 4, 8, 4, 3])

In [132]:
s = f * 2
s

array([10,  8, 16,  8,  6])

In [133]:
s_1 = f ** 3
s_1

array([125,  64, 512,  64,  27])

In [134]:
s_2 = f ** 0.5
s_2

array([2.23606798, 2.        , 2.82842712, 2.        , 1.73205081])

In [135]:
s_3 = f // 2
s_3

array([2, 2, 4, 2, 1])

In [136]:
s_4 = -1 ** f
s_4

array([-1, -1, -1, -1, -1])

Списки в Numpy ведут себя по другому

In [137]:
5 * [1, 2, 3, 4]

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

Альтернативные способы

In [138]:
# Вариант 1 (метод)
f.dot(-10)

array([-50, -40, -80, -40, -30])

In [139]:
# Вариант 2 (функция)
np.dot(-10, f)

array([-50, -40, -80, -40, -30])

In [140]:
# Вариант 3
np.multiply(-10, f)

array([-50, -40, -80, -40, -30])

##Скалярное произведение векторов

Векторы должны быть одинаковой размерности

In [141]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [142]:
sp = x[0] * y[0] + x[1] * y[1] + x[2] * y[2]
sp

32

In [143]:
x @ y

32

In [144]:
sp = np.dot(x, y)
sp

32

##Сложение и вычитание матриц

In [145]:
A = np.array([[0, 1], [2, 3], [4, 5]])
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [146]:
B = np.array([[6, 7], [8, 9], [10, 11]])
B

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [147]:
C = A + B
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

Альтернативный способ

In [148]:
C = np.add(A, B)
C

array([[ 6,  8],
       [10, 12],
       [14, 16]])

In [149]:
D = A - B
D

array([[-6, -6],
       [-6, -6],
       [-6, -6]])

In [150]:
D = np.subtract(B, A)
D

array([[6, 6],
       [6, 6],
       [6, 6]])

##Умножение матрицы на скаляр

In [151]:
B

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [152]:
X = B * 3
X

array([[18, 21],
       [24, 27],
       [30, 33]])

Альтернативный способ.

In [153]:
X = np.dot(B, 3)
X

array([[18, 21],
       [24, 27],
       [30, 33]])

#Применение Nympy для линейной алгебры - Часть 2

##Умножение и возведение в степень матриц

In [155]:
X1 = np.array([[1, 2], [3, 4], [5,6]])
X1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [157]:
X2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
X2

array([[ 7,  8,  9, 10],
       [11, 12, 13, 14]])

Число столбцов первой матрицы, должно равняться числу строк второй матрицы

In [160]:
print(X1.shape, X2.shape)

(3, 2) (2, 4)


In [158]:
X1.shape[1] == X2.shape[0]

True

In [168]:
Z = np.dot(X1, X2)
print(Z, '\n', Z.shape)

[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]] 
 (3, 4)


Как это считается?

In [169]:
Z[0, 0]

29

In [171]:
X1[0, 0] * X2[0, 0] + X1[0, 1] * X2[1, 0]

29

In [172]:
Z[0, 1] #Нулевой строки и 1 столбца

32

In [173]:
X1[0, 0] * X2[0, 1] + X1[0, 1] * X2[1, 1]

32

Возведение в степень

In [174]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Матрица должна быть квадратной
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [175]:
A_sq = np.dot(A, A)
A_sq

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [178]:
A_sq = np.linalg.matrix_power(A, 3) # Показатель степени: неотрицательное целое число
A_sq

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

##Единичная матрица
Единичная матрица - это квадратная матруца у которой по главной диагонали (левый верхний угол до правого нижнего) единицы, в остальных позициях нули.

In [179]:
I = np.eye(3, dtype=int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [180]:
C = np.dot(A_sq, I)
C

array([[ 468,  576,  684],
       [1062, 1305, 1548],
       [1656, 2034, 2412]])

31:57

##Транспонирование матриц

##Определитель и ранг матрицы

##Обратная матрица

##

##